---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tsmetrics
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: tsmetrics.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tsmetrics
                port:
                  number: 9100
