---
{{- if and (eq .Values.storage.type "pvc") (.Values.storage.pvc.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tsmetrics.fullname" . }}-state
  labels:
    {{- include "tsmetrics.labels" . | nindent 4 }}
  {{- with .Values.storage.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.storage.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.pvc.size }}
  {{- if .Values.storage.pvc.storageClass }}
  {{- if (eq "-" .Values.storage.pvc.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.storage.pvc.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}
