---
{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tsmetrics-secrets
type: Opaque
stringData:
  OAUTH_CLIENT_ID: {{ .Values.tailscale.oauthClientId | quote }}
  OAUTH_CLIENT_SECRET: {{ .Values.tailscale.oauthClientSecret | quote }}
  TAILNET_NAME: {{ .Values.tailscale.tailnetName | quote }}
  {{- if .Values.tailscale.tsnet.authKey }}
  TS_AUTHKEY: {{ .Values.tailscale.tsnet.authKey | quote }}
  {{- end }}
{{- end }}
