{{- if and (eq .Values.storage.type "k8s-secret") .Values.storage.kubeSecret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-state" (include "tsmetrics.fullname" .)) .Values.storage.kubeSecret.name }}
  labels:
    {{- include "tsmetrics.labels" . | nindent 4 }}
  {{- with .Values.storage.kubeSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data: {}
{{- end }}
