root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  cmd = "go build -ldflags \"-X main.version=${VERSION} -X main.buildTime=${BUILD_TIME}\" -o bin/tsmetrics ."
  bin = "bin/tsmetrics"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "deploy"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "USE_TSNET=true TSNET_HOSTNAME=tsmetrics-dev TSNET_TAGS=exporter REQUIRE_EXPORTER_TAG=true TARGET_DEVICES=gateway-140207,gateway-130104 ENV=development PORT=9100 bin/tsmetrics"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  stop_on_root = false

[color]
  app = "blue"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
