---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tsmetrics-state
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["tsmetrics-state"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
