#!/usr/bin/env bash
# Interactive .env onboarding.
# Runs before `dde project:up`. If .env already exists, this is a no-op.
# If .env is missing and a controlling terminal is available (/dev/tty),
# prompt for required credentials. In fully non-interactive contexts,
# fall back to copying .env.example and aborting.
set -euo pipefail

project_dir="${DDE_PROJECT_DIR:-$(pwd)}"
cd "$project_dir"

[ -f .env ] && exit 0

# dde pipes stdio to its hooks — talk to the terminal directly via /dev/tty.
if ! { [ -c /dev/tty ] && [ -r /dev/tty ] && [ -w /dev/tty ]; }; then
    cp .env.example .env
    echo "⚠  .env missing — copied from .env.example. Edit it, then re-run 'dde project:up'." >&2
    exit 1
fi

bold=$'\033[1m'; dim=$'\033[2m'; reset=$'\033[0m'

{
    echo ""
    echo "${bold}→ .env setup${reset}"
    echo "${dim}  Credentials erhältst du in der Tailscale Admin-Konsole:${reset}"
    echo "${dim}    https://login.tailscale.com/admin/settings/oauth${reset}"
    echo ""
} > /dev/tty

ask() {
    local var="$1" description="$2" default="${3:-}" value prompt
    if [ -n "$default" ]; then
        prompt="  ${var} (${description}) [${default}]: "
    else
        prompt="  ${var} (${description}): "
    fi
    printf '%s' "$prompt" > /dev/tty
    IFS= read -r value < /dev/tty
    value="${value:-$default}"
    printf '%s\n' "$value"
}

ask_secret() {
    local var="$1" description="$2" value
    printf '  %s (%s): ' "$var" "$description" > /dev/tty
    IFS= read -rs value < /dev/tty
    printf '\n' > /dev/tty
    printf '%s\n' "$value"
}

oauth_id=$(ask OAUTH_CLIENT_ID "Tailscale OAuth Client ID")
oauth_secret=$(ask_secret OAUTH_CLIENT_SECRET "Tailscale OAuth Client Secret")
tailnet=$(ask TAILNET_NAME "Tailnet name (z.B. yourcompany)")
auth_key=$(ask TS_AUTHKEY "Auth key for tsnet (leer lassen zum Überspringen)" "")
scrape_tag=$(ask SCRAPE_TAG "Tag that marks devices as scrape targets" "exporter")

cat > .env <<EOF
# tsmetrics — generated by .dde/hooks/project.up.pre/00-env.sh
# See .env.example for all available options.

# Tailscale API
OAUTH_CLIENT_ID=${oauth_id}
OAUTH_CLIENT_SECRET=${oauth_secret}
TAILNET_NAME=${tailnet}

# Scrape filter
SCRAPE_TAG=${scrape_tag}

# tsnet
USE_TSNET=true
TSNET_HOSTNAME=tsmetrics-dev
TSNET_TAGS=exporter
TS_AUTHKEY=${auth_key}
EOF

echo "" > /dev/tty
echo "✓ .env geschrieben." > /dev/tty
echo "" > /dev/tty
