apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsmetrics
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
        - name: tsmetrics
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: ENV
              value: "production"
            - name: SCRAPE_TAG
              value: "production"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: tsnet-state
              mountPath: /var/lib/tsmetrics/state
      volumes:
        - name: tsnet-state
          emptyDir: null
          persistentVolumeClaim:
            claimName: tsmetrics-state
