---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tsmetrics-state
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" # Use default storage class
