---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsmetrics
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:
        - name: tsmetrics
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: ENV
              value: "development"
            - name: TSNET_HOSTNAME
              value: "tsmetrics-dev"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
